{{- if .Values.accessEvents.secrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.fullname" . }}-access-events
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.accessEvents.secrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: {{ include "application.fullname" . }}-access-events-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.environment }}-access-events-secrets
      version: {{ .Values.accessEvents.secrets.version }}
{{- end }}
